export const API_ERROR_CONTRACT_VERSION = '1.0';

export enum ApiErrorCode {
  EYE_NOT_DETECTED = 'EYE_NOT_DETECTED',
  INVALID_IMAGE = 'INVALID_IMAGE',
  UNSUPPORTED_FORMAT = 'UNSUPPORTED_FORMAT',
  IMAGE_TOO_LARGE = 'IMAGE_TOO_LARGE',
  IMAGE_RESOLUTION_TOO_HIGH = 'IMAGE_RESOLUTION_TOO_HIGH',
  MODEL_LOADING = 'MODEL_LOADING',
  MODEL_TIMEOUT = 'MODEL_TIMEOUT',
  AI_SERVICE_UNAVAILABLE = 'AI_SERVICE_UNAVAILABLE',
  PREDICTION_FAILED = 'PREDICTION_FAILED',
  UPLOAD_FAILED = 'UPLOAD_FAILED',
  NO_INTERNET = 'NO_INTERNET',
  NETWORK_ERROR = 'NETWORK_ERROR',
  DATABASE_UNAVAILABLE = 'DATABASE_UNAVAILABLE',
  UNAUTHORIZED = 'UNAUTHORIZED',
  ANALYSIS_FAILED = 'ANALYSIS_FAILED',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  FORBIDDEN = 'FORBIDDEN',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  OTP_INVALID = 'OTP_INVALID',
  OTP_EXPIRED = 'OTP_EXPIRED',
  OTP_RATE_LIMITED = 'OTP_RATE_LIMITED',
  CHAT_NOT_FOUND = 'CHAT_NOT_FOUND',
}

export enum ErrorCategory {
  IMAGE = 'IMAGE',
  AI = 'AI',
  NETWORK = 'NETWORK',
  AUTH = 'AUTH',
  DATABASE = 'DATABASE',
  SYSTEM = 'SYSTEM',
  STORAGE = 'STORAGE',
  VALIDATION = 'VALIDATION',
  CONFIG = 'CONFIG',
}

export function isApiErrorCode(value: unknown): value is ApiErrorCode {
  return typeof value === 'string' && Object.values(ApiErrorCode).includes(value as ApiErrorCode);
}

export function isErrorCategory(value: unknown): value is ErrorCategory {
  return typeof value === 'string' && Object.values(ErrorCategory).includes(value as ErrorCategory);
}
