export enum AuditAction {
  USER_LOGGED_IN = 'USER_LOGGED_IN',
  USER_LOGGED_OUT = 'USER_LOGGED_OUT',
  USER_REGISTERED = 'USER_REGISTERED',
  USER_REFRESHED_TOKEN = 'USER_REFRESHED_TOKEN',
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_PROFILE_VIEWED = 'USER_PROFILE_VIEWED',
  ADMIN_VIEWED_ALL_USERS = 'ADMIN_VIEWED_ALL_USERS',
  FAILED_LOGIN = 'FAILED_LOGIN',
}

export enum AuditContext {
  AUTH = 'auth',
  USER = 'user',
  SYSTEM = 'system',
}
