export const DATABASE_UNAVAILABLE = 'DATABASE_UNAVAILABLE';
export const DATABASE_AUTHENTICATION_FAILED = 'DATABASE_AUTHENTICATION_FAILED';
export const DATABASE_CAPACITY_EXCEEDED = 'DATABASE_CAPACITY_EXCEEDED';
