export enum EnvKey {
  JWT_SECRET = 'JWT_SECRET',
  JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET',
  JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',
  JWT_REFRESH_EXPIRES_IN = 'JWT_REFRESH_EXPIRES_IN',
  DATABASE_URL = 'DATABASE_URL',
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',
}
