export enum EnvKey {
  JWT_SECRET = 'JWT_SECRET',
  JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET',
  JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',
  JWT_REFRESH_EXPIRES_IN = 'JWT_REFRESH_EXPIRES_IN',
  DATABASE_URL = 'DATABASE_URL',
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',
  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY',
  AWS_S3_BUCKET_NAME = 'AWS_S3_BUCKET_NAME',
  AWS_REGION = 'AWS_REGION',
}
