export interface PrivacySectionData {
  readonly title: string;
  readonly items: readonly string[];
}

export interface PrivacySecurityContent {
  readonly title: string;
  readonly subtitle: string;
  readonly sections: {
    readonly collection: PrivacySectionData;
    readonly usage: PrivacySectionData;
    readonly storage: PrivacySectionData;
    readonly security: PrivacySectionData;
    readonly disclaimer: PrivacySectionData;
    readonly rights: PrivacySectionData;
    readonly contact: PrivacySectionData;
  };
}
export const PRIVACY_SECURITY_CONTENT: PrivacySecurityContent = {
  title: 'Privacy Policy',
  subtitle:
    'Learn how we collect, use, protect, and manage your information while using SpandaVidya AI.',

  sections: {
    collection: {
      title: 'Information We Collect',
      items: [
        'We collect account information such as your name, email address, and authentication details when you register or sign in.',
        'We collect eye images that you voluntarily upload to use AI-powered cataract screening features.',
        'We may collect technical information including device type, operating system, application version, IP address, crash logs, and usage analytics to improve performance and reliability.',
        'We collect chat interactions and consultation history when you use AI assistance or health-related features within the application.',
      ],
    },

    usage: {
      title: 'How We Use Your Information',
      items: [
        'Uploaded eye images are processed to generate AI-based cataract screening results and related insights.',
        'Chat conversations and user inputs are used to provide AI-assisted responses and personalized application experiences.',
        'Information may be used to maintain account security, prevent abuse, troubleshoot issues, and improve application functionality.',
        'We do not sell, rent, or trade your personal information to third parties for marketing purposes.',
      ],
    },

    storage: {
      title: 'Data Storage & Retention',
      items: [
        'User information, uploaded images, and application records are stored on secure cloud infrastructure and managed databases.',
        'Data is retained only for as long as necessary to provide services, comply with legal obligations, resolve disputes, and enforce platform policies.',
        'When data is no longer required, reasonable steps are taken to securely delete or anonymize it in accordance with applicable requirements.',
      ],
    },

    security: {
      title: 'Security Practices',
      items: [
        'We implement industry-standard security measures designed to protect personal information against unauthorized access, disclosure, alteration, or loss.',
        'Data transmitted between the application and our servers is protected using secure communication protocols.',
        'Access to sensitive systems and user data is restricted to authorized personnel and services that require such access for operational purposes.',
      ],
    },

    disclaimer: {
      title: 'Medical & AI Disclaimer',
      items: [
        'The application provides AI-assisted screening and educational information only.',
        'Results generated by AI models should not be considered a medical diagnosis, treatment recommendation, or substitute for professional medical advice.',
        'Users should consult a qualified healthcare professional or ophthalmologist for medical evaluation, diagnosis, and treatment decisions.',
      ],
    },

    rights: {
      title: 'Your Rights & Choices',
      items: [
        'You may access, update, or correct your account information where such functionality is available.',
        'You may request deletion of your account and associated data by contacting our support team or using available account management features.',
        'You may discontinue use of the application at any time and withdraw permissions granted to the application through your device settings.',
      ],
    },

    contact: {
      title: 'Contact Us',
      items: [
        'If you have questions regarding this Privacy Policy, data handling practices, or privacy-related concerns, please contact us at support@spandavidyaai.com.',
        'Requests relating to account deletion, data access, or privacy concerns may be submitted through our official support channels.',
      ],
    },
  },
} as const;